### ISSUE TITLE
@radically-straightforward/html errors if interpolated value is not a string.

### ISSUE THREAD

**Issue by u-train** [radically-straightforward/radically-straightforward#11]
Right now, this code will cause an unintuitive error:
```js
console.log(
  html`
    <p> ${5} </p>
  `
) // TypeError: text.replaceAll is not a function
```
The work around is always to wrap your interpolated values that aren't strings (be it with `String()`, `.toFixed`, et cetera).

The fix would be in line 120, 124 128, and 130. Wrap the `substitutionPart` / `substitution` with `String()`.

**Comment by leafac** [comment]
Hi @u-train,

Thanks for reaching out.

As it turns out, this is intentional.

In TypeScript you’ll get a friendly error message: “Argument of type 'number' is not assignable to parameter of type 'string | string[]'.”

In JavaScript we don’t do a runtime check because it’s extra work and generating HTML is one of most common things we do on a server, so every bit of work counts.

And we don’t do a coercion like you mentioned because it often leads to issues when you forget to access a property of an object, for example, `${user}` when you really meant `${user.name}`, which would show up as `[object Object]` 😅

**Comment by u-train** [comment]
That's understandable, thank you for responding!
