### ISSUE TITLE
Would package be the replacement for caxa

### ISSUE THREAD

**Issue by prabhu** [radically-straightforward/radically-straightforward#8]
Hello,

Would package be the replacement for caxa? Is version 2 released [here](https://www.npmjs.com/package/@radically-straightforward/package) ready to be used? Following the instructions to run `npx package` didn't work for me so best to have some tests and example workflows for the same.

**Comment by jeffrson** [comment]
Well, I wonder if "package" ever was meant to be a replacement for caxa. Apparently it does nothing that can't be done with less than 5 minute shell scripting.
No offence, but there's a lot of features missing to use it for "packaging", and I don't mean the binary wrapper. Even the temporary copy has to be done in advance.
At least so far, "package" has a complete other purpose than caxa, which is (of course) disappointing, since caxa was said to be "migrated".

**Comment by aminya** [comment]
#15 adds the missing crucial options from caxa. It looks like this doesn't generate an executable. So it might be better to stick to Caxa if you want a self-contained executable

**Comment by leafac** [comment]
Hello y’all,

Yes, [`@radically-straightforward/package` is different from `caxa`](https://github.com/radically-straightforward/radically-straightforward/tree/13aeb78cf5644f63bf40d3af18543ada24adc8f7/package#caxa).

It’s true that it can be reproduced with a bit of shell scripting, and that’s the beauty of it: It took me years of playing around with more complex approaches to get here. For one thing, I don’t recommend the “self-contained executable” approach: it’s riddled with issues.

In any case, I don’t plan on supporting `caxa` anymore, but it’s perfectly functional, so feel free to take over that effort 🤗

**Comment by aminya** [comment]
@leafac I am interested in maintaining caxa. Could you un-deprecate the package and add me as a maintainer to the repository? 

https://docs.npmjs.com/adding-collaborators-to-private-packages-owned-by-a-user-account
https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions#undeprecating-a-package-or-version

**Comment by leafac** [comment]
Hi @aminya,

I love that you’ll bring the original idea of caxa back to life.

Please fork caxa and rename the project. I prefer that to undeprecating, because users will make the conscious decision of opting into a new project with a new maintainer.

And please keep me posted of how to goes. I’d love to see where you take my idea 🤗
